// Promotion: a finished brush program -> the edits that put it into the
// texture library, in the same shape the Task_FineTune.md workflow uses
// (code + texture_patterns.md + troubleshooting.md + CHANGELOG.md).
//
// Pure: every function takes the CURRENT file text and returns the new
// text. The page shows each change as a diff hunk and writes nothing until
// the author approves (library-io.js does the hash-checked writing).
//
// Every per-brush region is fenced by markers, so promoting again replaces
// (code, pattern entry) or extends (troubleshooting, status) that brush's
// own region and nothing else:
//   sketched_brushes.js   // <sketch-brush name="x" version="N"> ... // </sketch-brush>
//   *.md                  <!-- sketch-brush:x --> ... <!-- /sketch-brush:x -->

export const LIB_FILES = {
  code: "sketched_brushes.js",
  patterns: "texture_patterns.md",
  troubleshooting: "troubleshooting.md",
  changelog: "CHANGELOG.md",
};

const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** The exported names a brush adds to the library -- the library's own
 * convention (blobDot -> freeformBlobDotted): a trailing "Dot" is dropped
 * before "Dotted". */
export function exportNames(name) {
  const base = cap(name.replace(/Dot$/, "") || name);
  return {
    program: `${name}Program`,
    stamp: name,
    freeform: `freeform${base}Dotted`,
    brush: `brush${base}Dotted`,
  };
}

/** A program as readable JSON: one line per param and per step, so a
 * version diff shows which step changed. Valid JSON (and JS). */
export function formatProgram(p) {
  const lines = ["{"];
  const keys = Object.keys(p);
  keys.forEach((k, i) => {
    const comma = i < keys.length - 1 ? "," : "";
    const v = p[k];
    if (k === "params" && v && typeof v === "object" && Object.keys(v).length) {
      const ps = Object.entries(v);
      lines.push(`  "params": {`);
      ps.forEach(([pk, pv], j) => lines.push(`    ${JSON.stringify(pk)}: ${JSON.stringify(pv)}${j < ps.length - 1 ? "," : ""}`));
      lines.push(`  }${comma}`);
    } else if (k === "steps" && Array.isArray(v)) {
      lines.push(`  "steps": [`);
      v.forEach((st, j) => lines.push(`    ${JSON.stringify(st)}${j < v.length - 1 ? "," : ""}`));
      lines.push(`  ]${comma}`);
    } else {
      lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)}${comma}`);
    }
  });
  lines.push("}");
  return lines.join("\n");
}

export function programPath(name, version) { return `sketch_brushes/${name}/v${version}.program.json`; }
export function sketchPath(name, version) { return `sketch_brushes/${name}/v${version}.sketch.json`; }

// ------------------------------------------------------------------ code --

/** The version already in the library for `name`, or 0. */
export function libraryVersion(codeText, name) {
  const m = codeText.match(new RegExp(`// <sketch-brush name="${esc(name)}" version="(\\d+)">`));
  return m ? parseInt(m[1], 10) : 0;
}

/** Every brush in the library: [{name, version}]. */
export function libraryBrushes(codeText) {
  return [...codeText.matchAll(/\/\/ <sketch-brush name="([A-Za-z0-9]+)" version="(\d+)">/g)].map((m) => ({ name: m[1], version: parseInt(m[2], 10) }));
}

/** The program JSON embedded in the library for `name`, or null. */
export function libraryProgram(codeText, name) {
  const block = codeText.match(new RegExp(`// <sketch-brush name="${esc(name)}" version="\\d+">([\\s\\S]*?)// </sketch-brush>`));
  if (!block) return null;
  const m = block[1].match(new RegExp(`export const ${esc(name)}Program = ([\\s\\S]*?);\\n`));
  try { return m ? JSON.parse(m[1]) : null; } catch { return null; }
}

/** The generated block for one brush. Only literals and function
 * declarations at top level -- see the circular-import rule in the header
 * of sketched_brushes.js. */
export function codeBlock(program, { summary = "", date }) {
  const n = exportNames(program.name);
  const json = formatProgram(program);
  const params = Object.keys(program.params || {});
  const opts = [...params, "azimuthDeg", "gap", "reverse"].join(", ");
  return [
    `// <sketch-brush name="${program.name}" version="${program.version}">`,
    `// GENERATED by brush-sketch on ${date} from ${programPath(program.name, program.version)}.`,
    `// Edit the program (or use the page) and promote again -- do not hand-edit this block.`,
    `/** ${(summary || program.name).replace(/\*\//g, "* /")} */`,
    `export const ${n.program} = ${json};`,
    ``,
    `/** One ${program.name} stamp at (cx, cy) as a standalone printed element.`,
    ` * options: ${opts}. */`,
    `export function ${n.stamp}(em, cx, cy, options = {}) {`,
    `  return stampSketch(em, ${n.program}, cx, cy, options);`,
    `}`,
    ``,
    `/** ${program.name} stamps at arc-length \`gap\` along any path -- the`,
    ` * texture_functions.js line-style signature, so it also works as a fill() style. */`,
    `export function ${n.freeform}(em, xFunc, yFunc, tStart, tEnd, options = {}) {`,
    `  return freeformSketchDotted(em, ${n.program}, xFunc, yFunc, tStart, tEnd, options);`,
    `}`,
    ``,
    `/** parametric-with-tool brush shape: stamps along an arc-length-tagged point list. */`,
    `export function ${n.brush}(em, pts, options = {}) {`,
    `  return brushSketchDotted(em, ${n.program}, pts, options);`,
    `}`,
    ``,
    `SKETCH_BRUSHES.${program.name} = { program: ${n.program}, stamp: ${n.stamp}, freeform: ${n.freeform}, brush: ${n.brush} };`,
    `// </sketch-brush>`,
  ].join("\n");
}

/** New sketched_brushes.js text with this brush's block replaced or
 * appended inside the generated region. */
export function upsertCodeBlock(codeText, program, opts) {
  const block = codeBlock(program, opts);
  const existing = new RegExp(`// <sketch-brush name="${esc(program.name)}" version="\\d+">[\\s\\S]*?// </sketch-brush>`);
  if (existing.test(codeText)) return codeText.replace(existing, () => block);
  const end = "// </sketch-brushes>";
  const at = codeText.lastIndexOf(end);
  if (at < 0) throw new Error(`${LIB_FILES.code} has no "${end}" marker -- was the generated region edited by hand?`);
  return codeText.slice(0, at) + block + "\n\n" + codeText.slice(at);
}

// ------------------------------------------------------ markdown regions --

function regionRe(name) {
  return new RegExp(`<!-- sketch-brush:${esc(name)} -->[\\s\\S]*?<!-- /sketch-brush:${esc(name)} -->`);
}
function getRegion(text, name) {
  const m = text.match(regionRe(name));
  return m ? m[0] : null;
}
function wrap(name, body) {
  return `<!-- sketch-brush:${name} -->\n${body.trim()}\n<!-- /sketch-brush:${name} -->`;
}

const SKETCHED_HEADING = "## Sketched brushes";

// ------------------------------------------------------ texture_patterns --

/** The "Hardware status" bullets already recorded for a brush. */
export function statusBullets(patternsText, name) {
  const region = getRegion(patternsText, name);
  if (!region) return [];
  const at = region.indexOf("**Hardware status**:");
  if (at < 0) return [];
  return region.slice(at).split("\n").filter((l) => /^- /.test(l));
}

export function paramTable(program) {
  const rows = Object.entries(program.params || {}).map(([k, s]) =>
    `| \`${k}\` | ${s.level || "brush"} | ${s.def} | ${s.min}..${s.max} | ${String(s.desc || "").replace(/\|/g, "\\|")} |`);
  rows.push(`| \`azimuthDeg\` | brush | 0 | any | built-in: rotates the stamp, degrees CCW${program.orientation === "tangent" ? " -- an OFFSET from the path's local direction (orientation `tangent`)" : ""} |`);
  rows.push(`| \`gap\` | stroke | ${program.defaultGap ?? 10} | > 0 | built-in: arc-length spacing along a line |`);
  rows.push(`| \`reverse\` | stroke | false | bool | built-in: stamp the line end-to-start |`);
  return ["| Parameter | Level | Default | Range | Notes |", "|---|---|---|---|---|", ...rows].join("\n");
}

function patternsEntry(program, { description, date, statusLines }) {
  const n = exportNames(program.name);
  return wrap(program.name, [
    `### ${program.name} -- sketched brush, v${program.version}`,
    `\`${n.stamp}(em, cx, cy, options)\` · \`${n.freeform}(em, xFunc, yFunc, tStart, tEnd, options)\` · \`${n.brush}(em, pts, options)\``,
    ``,
    `Generated by the brush-sketch page into \`sketched_brushes.js\` (re-exported by \`texture_functions.js\`). Source of truth: \`${programPath(program.name, program.version)}\` -- edit the program, not the generated code. Orientation \`${program.orientation || "fixed"}\`, reach ${program.radiusMm ?? 10}mm.`,
    ``,
    description.trim(),
    ``,
    paramTable(program),
    ``,
    `**Hardware status**:`,
    ...statusLines,
  ].join("\n"));
}

/** New texture_patterns.md with this brush's entry added or replaced
 * (keeping its status history, plus one new bullet for this version). */
export function upsertPatternsEntry(patternsText, program, { description, date, testFile, origin }) {
  const prior = statusBullets(patternsText, program.name);
  const bullet = `- v${program.version} (${date}): ${origin}; **not yet print-tested**.${testFile ? ` Test file \`test_print_gcode/${testFile}\`.` : ""}`;
  const statusLines = [...prior.filter((l) => !l.startsWith(`- v${program.version} (`)), bullet];
  const entry = patternsEntry(program, { description, date, statusLines });
  if (getRegion(patternsText, program.name)) return patternsText.replace(regionRe(program.name), () => entry);
  let text = patternsText.replace(/\s*$/, "\n");
  if (!text.includes(`\n${SKETCHED_HEADING}\n`)) {
    text += `\n---\n\n${SKETCHED_HEADING}\n\nTextures prompted by DRAWING the nozzle's motion on the brush-sketch page (\`sewingeditor/brush-sketch/\`). Each is a brush program (JSON, in \`sketch_brushes/<name>/\`) run by one shared interpreter in \`sketched_brushes.js\`; the functions below are generated wrappers around it. Change a sketched brush by editing its program -- on the page, or by hand followed by promoting it again -- never by editing the generated block.\n`;
  }
  return text + "\n" + entry + "\n";
}

/** Adds one status bullet to an existing entry (after a print). */
export function appendStatus(patternsText, name, bullet) {
  const region = getRegion(patternsText, name);
  if (!region) throw new Error(`texture_patterns.md has no entry for "${name}"`);
  const updated = region.replace(`<!-- /sketch-brush:${name} -->`, `${bullet}\n<!-- /sketch-brush:${name} -->`);
  return patternsText.replace(regionRe(name), () => updated);
}

// -------------------------------------------------------- troubleshooting --

function nextSectionNumber(text) {
  const nums = [...text.matchAll(/^## (\d+)\./gm)].map((m) => parseInt(m[1], 10));
  return nums.length ? Math.max(...nums) + 1 : 1;
}

/** Appends a `### ...` subsection to the brush's section, creating the
 * section (next free number) the first time. */
export function appendTroubleshooting(tsText, name, subsection) {
  const region = getRegion(tsText, name);
  if (region) {
    const updated = region.replace(`<!-- /sketch-brush:${name} -->`, `${subsection.trim()}\n\n<!-- /sketch-brush:${name} -->`);
    return tsText.replace(regionRe(name), () => updated);
  }
  const n = nextSectionNumber(tsText);
  const section = wrap(name, [
    `## ${n}. Sketched brush: \`${name}\``,
    ``,
    `A texture prompted by drawing on the brush-sketch page. Its program history is in \`sketch_brushes/${name}/\`; each version below records what was drawn, what the page or the model changed to make it printable, and what the hardware said.`,
    ``,
    subsection.trim(),
    ``,
  ].join("\n"));
  return tsText.replace(/\s*$/, "\n") + "\n---\n\n" + section + "\n";
}

export function versionSubsection(program, { date, origin, changes, sequence, notes = [], digest, testFile }) {
  return [
    `### v${program.version} (${date})`,
    ``,
    `**Origin**: ${origin}. ${changes.trim()}`,
    ``,
    notes.length ? `**Changed from the drawing to make it printable**:\n${notes.map((x) => `- ${x.change} -- ${x.why}${x.ref ? ` (${x.ref})` : ""}`).join("\n")}\n` : `**Changed from the drawing**: nothing -- printed as drawn.\n`,
    `**One stamp, net G-code sequence**: ${sequence.trim()}`,
    ``,
    `**Verification** (page digest${testFile ? `, \`test_print_gcode/${testFile}\`` : ""}):`,
    "```",
    (digest || "(no test file generated)").trim(),
    "```",
    ``,
    `**Status**: not yet print-tested.`,
  ].join("\n");
}

export function printedSubsection(program, { date, report, analysis, testFile, proposed }) {
  return [
    `### v${program.version} printed (${date})`,
    ``,
    `**Reported**${testFile ? ` (\`test_print_gcode/${testFile}\`)` : ""}: "${report.trim()}"`,
    ``,
    `**Likely mechanism** (not confirmed): ${analysis.trim()}`,
    proposed ? `\n**Proposed next**: v${proposed.version} -- see the next subsection once promoted.` : "",
  ].join("\n");
}

// --------------------------------------------------------------- changelog --

export function appendChangelog(clText, { title, asked, given, problem = null }) {
  const nums = [...clText.matchAll(/^## (\d+)\./gm)].map((m) => parseInt(m[1], 10));
  const n = nums.length ? Math.max(...nums) + 1 : 1;
  const entry = [
    `## ${n}. ${title}`,
    ``,
    `**Asked**: ${asked.trim()}`,
    ``,
    ...(problem ? [`**Problem reported**: ${problem.trim()}`, ``] : []),
    `**Given**: ${given.trim()}`,
  ].join("\n");
  return { text: clText.replace(/\s*$/, "\n") + "\n---\n\n" + entry + "\n", number: n };
}

// -------------------------------------------------------------- whole set --

/**
 * Everything a promotion writes. `files` holds the current texts (keyed by
 * LIB_FILES values); returns [{path, before, after}] for the page to diff
 * and write, plus the new JSON files.
 */
export function buildPromotion({ files, program, doc, intent, origin, notes, digest, testFile, sketch, date }) {
  const out = [];
  const code = upsertCodeBlock(files[LIB_FILES.code], program, { summary: doc.summary, date });
  out.push({ path: LIB_FILES.code, before: files[LIB_FILES.code], after: code });

  const patterns = upsertPatternsEntry(files[LIB_FILES.patterns], program, { description: doc.description, date, testFile, origin });
  out.push({ path: LIB_FILES.patterns, before: files[LIB_FILES.patterns], after: patterns });

  const ts = appendTroubleshooting(files[LIB_FILES.troubleshooting], program.name,
    versionSubsection(program, { date, origin, changes: doc.changes, sequence: doc.sequence, notes, digest, testFile }));
  out.push({ path: LIB_FILES.troubleshooting, before: files[LIB_FILES.troubleshooting], after: ts });

  const n = exportNames(program.name);
  const cl = appendChangelog(files[LIB_FILES.changelog], {
    title: `Sketched brush \`${program.name}\` v${program.version}${doc.summary ? `: ${doc.summary}` : ""}`,
    asked: `${intent?.trim() ? `"${intent.trim()}"` : "(no intent line given)"} -- drawn on the brush-sketch page (${origin}); the drawing is kept in \`${sketchPath(program.name, program.version)}\`.`,
    given: [
      `\`${n.stamp}\` / \`${n.freeform}\` / \`${n.brush}\` generated into \`sketched_brushes.js\` from \`${programPath(program.name, program.version)}\`; entry in \`texture_patterns.md\` → Sketched brushes; version record in \`troubleshooting.md\`.`,
      doc.changes.trim(),
      testFile ? `Test file \`test_print_gcode/${testFile}\`. Page digest:\n\n\`\`\`\n${(digest || "").trim()}\n\`\`\`` : "No test file generated before promoting.",
      `**Not yet print-tested.**`,
    ].join("\n\n"),
  });
  out.push({ path: LIB_FILES.changelog, before: files[LIB_FILES.changelog], after: cl.text });

  const newFiles = [{ path: programPath(program.name, program.version), text: formatProgram(program) + "\n" }];
  if (sketch) newFiles.push({ path: sketchPath(program.name, program.version), text: JSON.stringify(sketch, null, 1) + "\n" });
  return { edits: out, newFiles, changelogNumber: cl.number };
}

/** Everything recording a print report. */
export function buildFeedback({ files, program, report, status, analysis, testFile, proposed, date }) {
  const bullet = `- v${program.version} printed (${date}): ${status.trim()}`;
  const patterns = appendStatus(files[LIB_FILES.patterns], program.name, bullet);
  const ts = appendTroubleshooting(files[LIB_FILES.troubleshooting], program.name, printedSubsection(program, { date, report, analysis, testFile, proposed }));
  const cl = appendChangelog(files[LIB_FILES.changelog], {
    title: `Sketched brush \`${program.name}\` v${program.version} printed`,
    asked: `print report for \`${program.name}\` v${program.version}${testFile ? ` (\`test_print_gcode/${testFile}\`)` : ""}.`,
    problem: `"${report.trim()}"`,
    given: `Recorded in \`texture_patterns.md\` (hardware status) and \`troubleshooting.md\`. Likely mechanism (not confirmed): ${analysis.trim()}${proposed ? ` A v${proposed.version} was proposed on the page; it is not in the library until promoted.` : ""}`,
  });
  return {
    edits: [
      { path: LIB_FILES.patterns, before: files[LIB_FILES.patterns], after: patterns },
      { path: LIB_FILES.troubleshooting, before: files[LIB_FILES.troubleshooting], after: ts },
      { path: LIB_FILES.changelog, before: files[LIB_FILES.changelog], after: cl.text },
    ],
    newFiles: [],
    changelogNumber: cl.number,
  };
}

/** The changed region of an edit as a compact hunk for display: common
 * prefix/suffix trimmed, a few lines of context kept. */
export function hunk(before, after, context = 2) {
  const a = before.split("\n"), b = after.split("\n");
  let s = 0;
  while (s < a.length && s < b.length && a[s] === b[s]) s++;
  let ea = a.length - 1, eb = b.length - 1;
  while (ea >= s && eb >= s && a[ea] === b[eb]) { ea--; eb--; }
  const from = Math.max(0, s - context);
  return {
    startLine: s + 1,
    removed: a.slice(s, ea + 1),
    added: b.slice(s, eb + 1),
    contextBefore: a.slice(from, s),
    contextAfter: a.slice(ea + 1, ea + 1 + context),
  };
}
