/**
 * texture_functions.js -- the complete, tested texture-generation library
 * for tactile G-code, ported from the validated Python version for
 * browser execution. This is the EXECUTION ENGINE: every texture should
 * be generated by calling functions from this file, never by re-deriving
 * geometry from scratch. See global_printing_parameters.md,
 * texture_patterns.md, and troubleshooting.md for reference documentation;
 * this file is ground truth when the two disagree.
 *
 * ============================================================================
 * SECTION 1: CORE INFRASTRUCTURE (Emitter, shared constants, e-rate math)
 * ============================================================================
 */

// ---------------------------------------------------------------- globals --
export const FILAMENT_DIA = 1.75;
export const FIL_AREA = Math.PI * (FILAMENT_DIA / 2) ** 2;

export const NOZZLE_TEMP = 232;   // TPU default -- see global_printing_parameters.md
export const BED_TEMP = 50;
export const RETRACT_MM = 1.3;
export const RETRACT_SPEED = 900; // 15mm/s -- slowed from 1500 (25mm/s); fast
                                   // retraction is suspected of damaging TPU
                                   // filament at the drive gear (see troubleshooting.md)
export const LINE_START_PRIME_MM = 0.3; // small extra extrusion applied once
                                   // per major printed element (see
                                   // Emitter.newPattern())

export const TRAVEL_SPEED = 3000;
export const Z_HOP = 0.4;
export const LAYER_HEIGHT = 0.20;
export const MIN_LAYERS = 2;      // 0.4mm floor -- see "Relief Height Floor"
                                   // in global_printing_parameters.md
export const DEFAULT_WIDTH = 0.5;
export const FLOW_PERCENT = 180;

export const BED_X = 220.0;
export const BED_Y = 220.0;

/** mm of filament per mm of XY travel, for a bead of given width/height. */
export function eRate(width, height, flowMult = 1.0) {
  return (width * height * flowMult) / FIL_AREA;
}

export function dist(a, b) {
  return Math.hypot(a[0] - b[0], a[1] - b[1]);
}

/**
 * Tracks running state (E, Z, XY, retracted-ness) across the whole file
 * and provides the common hop/travel/settle/retract primitives so every
 * texture function can be written as a small, self-contained unit.
 */
export class Emitter {
  constructor() {
    this.lines = [];
    this.eTotal = RETRACT_MM;
    this.x = null;
    this.y = null;
    this.z = null;
    this.retracted = true;
    this.pendingPrimeBonus = false;
  }

  a(s) {
    this.lines.push(s);
  }

  /**
   * Call once at the start of each top-level printed element (a line, a
   * fill region, a dot). Adds LINE_START_PRIME_MM the NEXT time the
   * pattern un-retracts -- once only. Does not affect internal
   * layer-to-layer or dot-to-dot un-retracts within the same element.
   */
  newPattern() {
    this.pendingPrimeBonus = true;
  }

  header({ nozzleTemp = NOZZLE_TEMP, bedTemp = BED_TEMP, flowPercent = FLOW_PERCENT } = {}) {
    const a = (s) => this.a(s);
    a("G21"); a("G90"); a("M82");
    a("M220 S100");
    a(`M221 S${flowPercent}`);
    a(`M104 S${nozzleTemp}`);
    a(`M140 S${bedTemp}`);
    a(`M190 S${bedTemp}`);
    a(`M109 S${nozzleTemp}`);
    a("G28");
    a("G92 E0");
    a("G1 Z5 F3000");
    a("G1 X10 Y15 Z0.28 F5000");
    a("G1 X10 Y100 Z0.28 F1500 E12");
    a("G1 X10.4 Y100 Z0.28 F5000");
    a("G1 X10.4 Y15 Z0.28 F1500 E24");
    a("G92 E0");
    a("G1 Z2.0 F3000");
    a(`G92 E${RETRACT_MM.toFixed(3)}`);
    this.eTotal = RETRACT_MM;
    this.x = 10.4; this.y = 15.0; this.z = 2.0;
    this.retracted = true;
  }

  footer() {
    const a = (s) => this.a(s);
    a("G91");
    if (!this.retracted) {
      a(`G1 E${(-RETRACT_MM).toFixed(3)} F${RETRACT_SPEED}`);
    }
    a("G1 Z10 F3000");
    a("G90");
    a(`G1 X0 Y${(BED_Y - 2).toFixed(0)} F3000`);
    a("M104 S0"); a("M140 S0"); a("M84");
  }

  /** Hop to a safe height, travel, settle, un-retract-if-needed. */
  goto(x, y, z) {
    const hopZ = Math.max(z, this.z ?? 0) + Z_HOP;
    this.a(`G1 Z${hopZ.toFixed(3)} F3000`);
    if (!this.retracted) {
      this.eTotal -= RETRACT_MM;
      this.a(`G1 E${this.eTotal.toFixed(4)} F${RETRACT_SPEED}`);
      this.retracted = true;
    }
    this.a(`G0 X${x.toFixed(3)} Y${y.toFixed(3)} F${TRAVEL_SPEED}`);
    this.a(`G1 Z${z.toFixed(3)} F1500`);
    this.x = x; this.y = y; this.z = z;
  }

  unretract() {
    if (this.retracted) {
      const bonus = this.pendingPrimeBonus ? LINE_START_PRIME_MM : 0.0;
      this.pendingPrimeBonus = false;
      this.eTotal += RETRACT_MM + bonus;
      this.a(`G1 E${this.eTotal.toFixed(4)} F${RETRACT_SPEED}`);
      this.retracted = false;
    }
  }

  retract() {
    if (!this.retracted) {
      this.eTotal -= RETRACT_MM;
      this.a(`G1 E${this.eTotal.toFixed(4)} F${RETRACT_SPEED}`);
      this.retracted = true;
    }
  }

  printMove(x, y, eAdd, speed, z = null) {
    this.eTotal += eAdd;
    const zpart = z !== null ? ` Z${z.toFixed(3)}` : "";
    this.a(`G1 X${x.toFixed(3)} Y${y.toFixed(3)}${zpart} E${this.eTotal.toFixed(4)} F${speed.toFixed(0)}`);
    this.x = x; this.y = y;
    if (z !== null) this.z = z;
  }

  dwell(ms) {
    this.a(`G4 P${Math.round(ms)}`);
  }
}

export function stripComments(text) {
  const out = [];
  for (const rawLine of text.split("\n")) {
    let line = rawLine;
    const idx = line.indexOf(";");
    if (idx !== -1) line = line.slice(0, idx).replace(/\s+$/, "");
    if (line.trim()) out.push(line);
  }
  return out.join("\n") + "\n";
}

/** Points for a solid filled circular dot. */
export function spiralDisc(center, radius, spacing = 0.28, ptsPerTurn = 20) {
  const nTurns = Math.max(1, Math.ceil(radius / spacing));
  const nPts = nTurns * ptsPerTurn;
  const pts = [];
  for (let k = 0; k <= nPts; k++) {
    const theta = (k * (nTurns * 2 * Math.PI)) / nPts;
    const r = radius * (theta / (nTurns * 2 * Math.PI));
    pts.push([center[0] + r * Math.cos(theta), center[1] + r * Math.sin(theta)]);
  }
  return pts;
}

/**
 * ============================================================================
 * SECTION 2: FREEFORM PATH ENGINE
 * ============================================================================
 * Any line can follow x(t), y(t) -- a straight line, an angle, a sine
 * wiggle, an arc, or a hand-authored curve -- not just a hardcoded
 * horizontal line. Includes safety checks: naive fixed-count sampling can
 * produce near-180-degree spikes on non-uniform-speed curves, and some
 * requested shapes (e.g. amplitude exceeding wavelength) are too steep to
 * print smoothly at ANY sampling resolution. Both are caught here rather
 * than silently producing bad G-code.
 */

/**
 * The path has a direction change too sharp to print smoothly, even
 * after refining sampling. This means the SHAPE is the problem (e.g.
 * amplitude exceeding wavelength), not the resolution -- resampling
 * finer will not fix it. Reduce amplitude or increase wavelength/radius.
 */
export class PathTooSteepError extends Error {
  constructor(message) {
    super(message);
    this.name = "PathTooSteepError";
  }
}

function turnAngleDeg(p0, p1, p2) {
  const v1 = [p1[0] - p0[0], p1[1] - p0[1]];
  const v2 = [p2[0] - p1[0], p2[1] - p1[1]];
  const a1 = Math.atan2(v1[1], v1[0]);
  const a2 = Math.atan2(v2[1], v2[0]);
  let turn = Math.abs(((a2 - a1) * 180) / Math.PI);
  return turn > 180 ? 360 - turn : turn;
}

/**
 * Samples (xFunc(t), yFunc(t)) at a fixed, fine step (deliberately NOT
 * adaptive -- adaptive sampling math is itself an easy place to
 * introduce subtle bugs). Verifies no consecutive-segment turn exceeds
 * maxTurnDeg; refines (halves step) up to maxRefineAttempts times; throws
 * PathTooSteepError if the violation persists.
 * Returns array of [x, y, s], s = cumulative arc length from tStart.
 */
export function samplePath(xFunc, yFunc, tStart, tEnd, {
  step = 0.1, maxTurnDeg = 15.0, maxRefineAttempts = 3,
} = {}) {
  const doSample = (step) => {
    const pts = [];
    let t = tStart;
    while (t < tEnd - 1e-9) {
      pts.push([xFunc(t), yFunc(t)]);
      t += step;
    }
    pts.push([xFunc(tEnd), yFunc(tEnd)]);
    return pts;
  };

  const maxTurn = (pts) => {
    let worst = 0.0;
    for (let i = 1; i < pts.length - 1; i++) {
      worst = Math.max(worst, turnAngleDeg(pts[i - 1], pts[i], pts[i + 1]));
    }
    return worst;
  };

  let pts = doSample(step);
  let attempts = 0;
  let prevWorst = null;
  let curStep = step;
  while (true) {
    const worst = maxTurn(pts);
    if (worst <= maxTurnDeg) break;
    if (attempts >= maxRefineAttempts) {
      throw new PathTooSteepError(
        `Path has a ${worst.toFixed(1)} degree direction change that ` +
        `persists after ${attempts} sampling refinements ` +
        `(step=${curStep.toFixed(4)}mm). Reduce amplitude or increase ` +
        `wavelength/radius rather than resampling further.`
      );
    }
    if (prevWorst !== null && worst >= prevWorst * 0.98) {
      throw new PathTooSteepError(
        `Path has a ${worst.toFixed(1)} degree direction change NOT ` +
        `improving with finer sampling (was ${prevWorst.toFixed(1)} ` +
        `degrees before refinement) -- the shape itself is too steep, ` +
        `not a resolution problem.`
      );
    }
    prevWorst = worst;
    curStep /= 2.0;
    pts = doSample(curStep);
    attempts += 1;
  }

  const out = [[pts[0][0], pts[0][1], 0.0]];
  let s = 0.0;
  for (let i = 1; i < pts.length; i++) {
    s += Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]);
    out.push([pts[i][0], pts[i][1], s]);
  }
  return out;
}

/** Interpolates the (x,y) position at a specific arc-length distance
 * along a samplePath() result. */
export function pointAtArcLength(sampledPts, targetS) {
  if (targetS <= 0) return [sampledPts[0][0], sampledPts[0][1]];
  const last = sampledPts[sampledPts.length - 1];
  if (targetS >= last[2]) return [last[0], last[1]];
  let lo = 0, hi = sampledPts.length - 1;
  while (lo < hi - 1) {
    const mid = Math.floor((lo + hi) / 2);
    if (sampledPts[mid][2] <= targetS) lo = mid; else hi = mid;
  }
  const [x0, y0, s0] = sampledPts[lo];
  const [x1, y1, s1] = sampledPts[hi];
  const frac = s1 === s0 ? 0.0 : (targetS - s0) / (s1 - s0);
  return [x0 + frac * (x1 - x0), y0 + frac * (y1 - y0)];
}

export function totalLength(sampledPts) {
  return sampledPts[sampledPts.length - 1][2];
}

/**
 * ============================================================================
 * SECTION 3: LINE STYLES (all six follow the freeform path engine above --
 * none are hardcoded to horizontal)
 * ============================================================================
 */

/** Continuous solid line following any path. */
export function freeformSolid(em, xFunc, yFunc, tStart, tEnd, {
  width = 0.5, nLayers = 2, speed = 400, step = 0.1,
} = {}) {
  const pts = samplePath(xFunc, yFunc, tStart, tEnd, { step });
  em.newPattern();
  for (let layer = 1; layer <= nLayers; layer++) {
    const z = LAYER_HEIGHT * layer;
    em.goto(pts[0][0], pts[0][1], z);
    em.unretract();
    for (let i = 1; i < pts.length; i++) {
      const [x0, y0] = pts[i - 1], [x1, y1] = pts[i];
      const seg = Math.hypot(x1 - x0, y1 - y0);
      if (seg < 1e-9) continue;
      em.printMove(x1, y1, seg * eRate(width, LAYER_HEIGHT), speed);
    }
    em.retract();
  }
  return pts;
}

/** Dashed line following any path -- segLen/gapLen measured along actual
 * arc length, not the raw t parameter. */
export function freeformDashed(em, xFunc, yFunc, tStart, tEnd, {
  segLen, gapLen, width = 0.5, nLayers = 2, speed = 400, step = 0.1,
} = {}) {
  if (typeof segLen !== "number" || typeof gapLen !== "number") {
    throw new TypeError(
      "freeformDashed requires numeric segLen and gapLen in its options " +
      "object, e.g. {segLen: 8, gapLen: 4}. (These were positional " +
      "parameters in an earlier version -- moved into options so that ALL " +
      "line styles share one identical signature and are genuinely " +
      "interchangeable as fill() styles. See troubleshooting.md section 8.)"
    );
  }
  const pts = samplePath(xFunc, yFunc, tStart, tEnd, { step });
  const length = totalLength(pts);
  em.newPattern();
  let s = 0.0;
  while (s < length - 1e-6) {
    const s2 = Math.min(s + segLen, length);
    const subStart = pointAtArcLength(pts, s);
    let subPts = pts.filter((p) => p[2] >= s && p[2] <= s2);
    if (subPts.length === 0 || subPts[0][2] > s + 1e-6) {
      subPts = [[subStart[0], subStart[1], s], ...subPts];
    }
    for (let layer = 1; layer <= nLayers; layer++) {
      const z = LAYER_HEIGHT * layer;
      em.goto(subPts[0][0], subPts[0][1], z);
      em.unretract();
      for (let i = 1; i < subPts.length; i++) {
        const [x0, y0] = subPts[i - 1], [x1, y1] = subPts[i];
        const seg = Math.hypot(x1 - x0, y1 - y0);
        if (seg < 1e-9) continue;
        em.printMove(x1, y1, seg * eRate(width, LAYER_HEIGHT), speed);
      }
      em.retract();
    }
    s = s2 + gapLen;
  }
  return pts;
}

/** Dots stamped at regular ARC-LENGTH intervals along any path. */
export function freeformDotted(em, xFunc, yFunc, tStart, tEnd, {
  gap = 10.0, dotRadius = 0.8, nLayers = 2, speed = 250, step = 0.1,
} = {}) {
  const pts = samplePath(xFunc, yFunc, tStart, tEnd, { step });
  const length = totalLength(pts);
  em.newPattern();
  let s = 0.0;
  while (s <= length + 1e-6) {
    const [cx, cy] = pointAtArcLength(pts, s);
    const dotPts = spiralDisc([cx, cy], dotRadius);
    for (let layer = 1; layer <= nLayers; layer++) {
      const z = LAYER_HEIGHT * layer;
      em.goto(dotPts[0][0], dotPts[0][1], z);
      em.unretract();
      for (let i = 1; i < dotPts.length; i++) {
        const seg = dist(dotPts[i - 1], dotPts[i]);
        if (seg < 1e-9) continue;
        em.printMove(dotPts[i][0], dotPts[i][1], seg * eRate(0.42, LAYER_HEIGHT), speed);
      }
      em.retract();
    }
    s += gap;
  }
  return pts;
}

/** Dots stamped by the blobDot() point-extrusion mechanism (see SECTION 5
 * below) at regular arc-length intervals along any path -- the DEFAULT
 * dotted-line style, preferred over freeformDotted() unless a flat,
 * spiral-filled disc is specifically needed. Shares the six-line-style
 * signature (em, xFunc, yFunc, tStart, tEnd, options) so it is safely
 * interchangeable as a fill() style. */
export function freeformBlobDotted(em, xFunc, yFunc, tStart, tEnd, {
  gap = 10.0, diameter = 1.6, baseZ = 0.3, extrudeSpeed = 300, dwellMs = 400,
  extrusionMultiplier = 1.0, liftZ = 2.0, liftSpeed = 600, liftDwellMs = 200,
  pressDwellMs = 150, pressSpeed = 600, step = 0.1,
} = {}) {
  const pts = samplePath(xFunc, yFunc, tStart, tEnd, { step });
  const length = totalLength(pts);
  em.newPattern();
  let s = 0.0;
  while (s <= length + 1e-6) {
    const [cx, cy] = pointAtArcLength(pts, s);
    emitBlobDot(em, cx, cy, {
      diameter, baseZ, extrudeSpeed, dwellMs, extrusionMultiplier,
      liftZ, liftSpeed, liftDwellMs, pressDwellMs, pressSpeed,
    });
    s += gap;
  }
  return pts;
}

/** Vertical-lift hair strands stamped at regular arc-length intervals
 * along any path. CAUTION: each strand is a retract/un-retract cycle --
 * see troubleshooting.md on retraction-cycle-count and TPU filament
 * damage before using a dense spacing over a long path. */
export function freeformHairy(em, xFunc, yFunc, tStart, tEnd, {
  spacing = 5.0, esegmentMm = 1.2, retractMm = 1.3, dwellMs = 400,
  smallLift = 0.2, bigLift = 4.0, baseZ = 0.3, speed = 200, step = 0.1,
} = {}) {
  const pts = samplePath(xFunc, yFunc, tStart, tEnd, { step });
  const length = totalLength(pts);
  em.newPattern();
  const nRoots = Math.floor(length / spacing) + 1;
  const first = pointAtArcLength(pts, 0);
  em.goto(first[0], first[1], baseZ);
  em.unretract();
  for (let i = 0; i < nRoots; i++) {
    const s = i * spacing;
    em.eTotal += esegmentMm;
    em.a(`G1 E${em.eTotal.toFixed(4)} F500`);
    const z1 = baseZ + smallLift;
    em.a(`G0 Z${z1.toFixed(3)}`);
    em.z = z1;
    em.dwell(dwellMs);
    const z2 = z1 + bigLift;
    em.a(`G0 Z${z2.toFixed(3)} F600`);
    em.z = z2;
    em.eTotal -= retractMm;
    em.a(`G1 E${em.eTotal.toFixed(4)} F${RETRACT_SPEED}`);
    if (i < nRoots - 1) {
      const [nx, ny] = pointAtArcLength(pts, s + spacing);
      em.a(`G0 X${nx.toFixed(3)} Y${ny.toFixed(3)} F${speed}`);
      em.x = nx; em.y = ny;
    }
    em.a(`G0 Z${baseZ.toFixed(3)} F600`);
    em.z = baseZ;
    em.eTotal += retractMm;
  }
  em.retracted = true;
  return pts;
}

/** Alternating normal/fat-rate segments following any path. Uses RELATIVE
 * mode (G91/M83) for the whole segmented run -- this specific mechanism is
 * validated against real hardware; see troubleshooting.md before changing it. */
export function freeformSegmented(em, xFunc, yFunc, tStart, tEnd, {
  segLen, z = 0.2, esegment = 0.5, multiplier = 4, retractMm = 4.0,
  retractSpeed = 1000, fm = 400, eprime = 4.0, primedwellS = 1.0, step = 0.1,
} = {}) {
  if (typeof segLen !== "number") {
    throw new TypeError(
      "freeformSegmented requires a numeric segLen in its options object, " +
      "e.g. {segLen: 10}. (This was a positional parameter in an earlier " +
      "version -- moved into options so that ALL line styles share one " +
      "identical signature and are genuinely interchangeable as fill() " +
      "styles. See troubleshooting.md section 8.)"
    );
  }
  const pts = samplePath(xFunc, yFunc, tStart, tEnd, { step });
  const length = totalLength(pts);
  const nSegments = Math.round(length / segLen);
  em.newPattern();

  const first = pointAtArcLength(pts, 0);
  em.goto(first[0], first[1], z);
  em.eTotal += eprime;
  em.a(`G1 E${em.eTotal.toFixed(4)} F150`);
  em.dwell(primedwellS * 1000);
  em.retracted = false;

  em.a("G91");
  em.a("M83");
  let [curX, curY] = first;
  for (let i = 0; i < nSegments; i++) {
    const s1 = Math.min((i + 1) * segLen, length);
    const [nx, ny] = pointAtArcLength(pts, s1);
    const dx = nx - curX, dy = ny - curY;
    const segDist = Math.hypot(dx, dy);
    const mult = (i % 2 === 1) ? multiplier : 1;
    const eAmt = segDist * esegment * mult;
    em.a(`G1 X${dx.toFixed(3)} Y${dy.toFixed(3)} E${eAmt.toFixed(4)} F${fm}`);
    curX = nx; curY = ny;
    if (i < nSegments - 1) {
      em.a(`G1 E${(-retractMm).toFixed(4)} F${retractSpeed}`);
    }
  }
  em.a(`G1 E${(-retractMm).toFixed(4)} F${retractSpeed}`);
  em.a("G90");
  em.a("M82");
  em.x = curX; em.y = curY; em.z = z;
  em.retracted = true;
  return pts;
}

/** The sine-wave bulge technique, generalized to follow any path --
 * height varies as a function of ARC LENGTH along the path, not of x.
 * hMax/zGap defaults are user-validated as not flat -- see
 * global_printing_parameters.md change log before lowering zGap. */
export function freeformVariableThickness(em, xFunc, yFunc, tStart, tEnd, {
  hMin = 0.16, hMax = 0.9, wavelength = 8.0, beadWidth = 0.8,
  zGap = 0.25, speed = 25, peakDwellMs = 300, step = 0.1,
} = {}) {
  const pts = samplePath(xFunc, yFunc, tStart, tEnd, { step });
  em.newPattern();

  const hAt = (s) => hMin + (hMax - hMin) * 0.5 * (1 + Math.sin((2 * Math.PI * s) / wavelength));

  const firstH = hAt(0);
  em.goto(pts[0][0], pts[0][1], firstH + zGap);
  em.unretract();
  let prevH = firstH;
  for (let i = 1; i < pts.length; i++) {
    const [x0, y0] = pts[i - 1], [x1, y1, s1] = pts[i];
    const seg = Math.hypot(x1 - x0, y1 - y0);
    if (seg < 1e-9) continue;
    const h1 = hAt(s1);
    const hAvg = (prevH + h1) / 2.0;
    em.printMove(x1, y1, seg * eRate(beadWidth, hAvg), speed, h1 + zGap);
    prevH = h1;
  }
  em.retract();
  return pts;
}

/**
 * ============================================================================
 * SECTION 4: REGIONS AND FILLS
 * ============================================================================
 * A region is {x0, y0, w, h} -- an axis-aligned rectangle. This is
 * deliberately the ONLY region type implemented right now, because it is
 * the only one this project has actually needed. Polygon and circle
 * regions are a natural extension (see troubleshooting.md "Polygon
 * winding order" for a real gotcha to avoid) but are NOT implemented here.
 *
 * CRITICAL: diamond fill is NOT a generic "lines at a gap" pattern, even
 * though it looks like one. Its lattice lines fit the generic mechanism,
 * but WHICH cells get filled solid is a discrete checkerboard-parity
 * selection with no `gap` value that produces it as a side effect. This
 * is also the single most bug-prone algorithm in this project (four
 * attempts to get right, verified only by explicit adjacency checking,
 * not visual inspection). It is therefore its OWN dedicated function,
 * never routed through fillRegion(), even though fill() below presents
 * both through one consistent-looking call.
 */

/** Exact (Liang-Barsky) clip of the infinite line (px,py)+s*(dx,dy)
 * against [x0,x1]x[y0,y1]. Returns [pStart,pEnd] or null if it misses. */
export function clipLineToRect(px, py, dx, dy, x0, y0, x1, y1) {
  let tMin = -Infinity, tMax = Infinity;
  const axes = [[px, dx, x0, x1], [py, dy, y0, y1]];
  for (const [p, d, lo, hi] of axes) {
    if (Math.abs(d) < 1e-12) {
      if (p < lo || p > hi) return null;
      continue;
    }
    let t0 = (lo - p) / d;
    let t1 = (hi - p) / d;
    if (t0 > t1) [t0, t1] = [t1, t0];
    tMin = Math.max(tMin, t0);
    tMax = Math.min(tMax, t1);
    if (tMin > tMax) return null;
  }
  return [[px + tMin * dx, py + tMin * dy], [px + tMax * dx, py + tMax * dy]];
}

/** Returns the clipped [start,end] line segments needed to fill `region`
 * with parallel lines at `angleDeg`, `gap` apart. Recomputes from scratch
 * every call -- this is what makes "change the gap" a correct, automatic
 * operation rather than manual line-list editing. */
export function regionFillLines(region, angleDeg, gap) {
  const { x0, y0, w, h } = region;
  const x1 = x0 + w, y1 = y0 + h;
  const theta = (angleDeg * Math.PI) / 180;
  const dx = Math.cos(theta), dy = Math.sin(theta);
  const nx = -Math.sin(theta), ny = Math.cos(theta);

  const corners = [[x0, y0], [x1, y0], [x0, y1], [x1, y1]];
  const perpVals = corners.map(([cx, cy]) => cx * nx + cy * ny);
  const pMin = Math.min(...perpVals), pMax = Math.max(...perpVals);

  const segments = [];
  for (let p = pMin; p <= pMax; p += gap) {
    const px = p * nx, py = p * ny;
    const clipped = clipLineToRect(px, py, dx, dy, x0, y0, x1, y1);
    if (clipped) {
      const [[ax, ay], [bx, by]] = clipped;
      if (Math.hypot(bx - ax, by - ay) > 1e-6) segments.push(clipped);
    }
  }
  return segments;
}

/** Generic fill: clip parallel lines across `region` at `angleDeg`, `gap`
 * apart, drawn with `styleFunc` (any freeform* line style). NEVER use
 * this for diamond fill -- see module docstring above. */
export function fillRegion(em, region, styleFunc, { angleDeg = 0, gap = 4.0, ...styleOptions } = {}) {
  const segments = regionFillLines(region, angleDeg, gap);
  for (const [p0, p1] of segments) {
    const ddx = p1[0] - p0[0], ddy = p1[1] - p0[1];
    const length = Math.hypot(ddx, ddy);
    if (length < 1e-6) continue;
    const ux = ddx / length, uy = ddy / length;
    const xFunc = (t) => p0[0] + t * ux;
    const yFunc = (t) => p0[1] + t * uy;
    styleFunc(em, xFunc, yFunc, 0, length, styleOptions);
  }
}

function clipLineFamilyRegion(x0, y0, w, h, constVal, family) {
  const nScan = 200;
  let prevValid = false, runStart = null, prevPt = null, result = null;
  for (let k = 0; k <= nScan; k++) {
    const px = x0 + (w * k) / nScan;
    const py = family === "diff" ? px - constVal : constVal - px;
    const valid = py >= y0 && py <= y0 + h;
    if (valid && !prevValid) runStart = [px, py];
    if (!valid && prevValid) { result = [runStart, prevPt]; break; }
    prevValid = valid;
    prevPt = [px, py];
  }
  if (result === null && prevValid) result = [runStart, prevPt];
  return result;
}

/** Standard multi-layer stroke: print `points` as a path, nLayers times,
 * each pass a full layer higher. */
export function emitStroke(em, points, nLayers, width, speed) {
  for (let layer = 1; layer <= nLayers; layer++) {
    const z = LAYER_HEIGHT * layer;
    em.goto(points[0][0], points[0][1], z);
    em.unretract();
    for (let i = 1; i < points.length; i++) {
      const seg = dist(points[i - 1], points[i]);
      if (seg < 1e-9) continue;
      em.printMove(points[i][0], points[i][1], seg * eRate(width, LAYER_HEIGHT), speed);
    }
    em.retract();
  }
}

/** Diamond lattice with checkerboard fill. region={x0,y0,w,h}. Indexes
 * diamonds by their TRUE rotated-square-grid coordinates (i,j) via
 * center=(x0+half*(i+j), y0+half*(i-j)), checkerboard parity=(i+j)%2 --
 * the mathematically correct rule (see troubleshooting.md "Diamond
 * checkerboard parity" for the four-attempt history behind this).
 * DO NOT reimplement this via fillRegion() -- see module docstring. */
export function diamondFillRegion(em, region, { diag = 8.0, fillGap = 0.6 } = {}) {
  const { x0, y0, w, h } = region;
  em.newPattern();
  const half = diag / 2.0;

  const diamonds = [];
  const N = Math.floor((w + h) / diag) + 3;
  for (let i = -N; i <= N; i++) {
    for (let j = -N; j <= N; j++) {
      const cx = x0 + half * (i + j);
      const cy = y0 + half * (i - j);
      if (cx < x0 - diag || cx > x0 + w + diag) continue;
      if (cy < y0 - diag || cy > y0 + h + diag) continue;
      diamonds.push([cx, cy, (i + j) % 2 === 0]);
    }
  }

  const diffConsts = new Set(), sumConsts = new Set();
  for (const [cx, cy] of diamonds) {
    diffConsts.add(Math.round((cx - cy - half) * 10000) / 10000);
    diffConsts.add(Math.round((cx - cy + half) * 10000) / 10000);
    sumConsts.add(Math.round((cx + cy - half) * 10000) / 10000);
    sumConsts.add(Math.round((cx + cy + half) * 10000) / 10000);
  }

  for (const c of [...diffConsts].sort((a, b) => a - b)) {
    const seg = clipLineFamilyRegion(x0, y0, w, h, c, "diff");
    if (seg) emitStroke(em, seg, 2, 0.4, 400);
  }
  for (const c of [...sumConsts].sort((a, b) => a - b)) {
    const seg = clipLineFamilyRegion(x0, y0, w, h, c, "sum");
    if (seg) emitStroke(em, seg, 2, 0.4, 400);
  }

  for (const [cx, cy, filled] of diamonds) {
    if (!filled) continue;
    for (let yy = cy - half + fillGap; yy < cy + half - 1e-6; yy += fillGap) {
      if (yy >= y0 && yy <= y0 + h) {
        const ww = half - Math.abs(yy - cy);
        if (ww > 0.05) {
          const xa = Math.max(x0, cx - ww);
          const xb = Math.min(x0 + w, cx + ww);
          if (xb > xa) emitStroke(em, [[xa, yy], [xb, yy]], 2, 0.4, 450);
        }
      }
    }
  }
  return diamonds;
}

/** Explicit adjacency verification -- the ONLY acceptable way to confirm
 * diamond fill correctness. Visual inspection is NOT sufficient. Always
 * call this after generating/modifying diamond fill and confirm
 * violations === 0 before trusting the output. */
export function verifyCheckerboard(diamonds, diag) {
  const half = diag / 2.0;
  const lookup = new Map();
  for (const [cx, cy, filled] of diamonds) {
    lookup.set(`${Math.round(cx * 1000) / 1000},${Math.round(cy * 1000) / 1000}`, filled);
  }
  let checked = 0, violations = 0;
  const offsets = [[half, half], [half, -half], [-half, half], [-half, -half]];
  for (const [cx, cy, filled] of diamonds) {
    for (const [ddx, ddy] of offsets) {
      const key = `${Math.round((cx + ddx) * 1000) / 1000},${Math.round((cy + ddy) * 1000) / 1000}`;
      if (lookup.has(key)) {
        checked += 1;
        if (lookup.get(key) === filled) violations += 1;
      }
    }
  }
  return { checked, violations };
}

// pass as `style` to fill() to request diamond fill
export const DIAMOND = "__diamond__";

/** THE single unified entry point for all fills. `style` is either
 * DIAMOND (routed to the dedicated diamond algorithm) or any freeform*
 * line-style function (routed through fillRegion()). Callers never need
 * to know this split exists. */
export function fill(em, region, style, options = {}) {
  if (style === DIAMOND) {
    return diamondFillRegion(em, region, options);
  } else {
    return fillRegion(em, region, style, options);
  }
}

/**
 * ============================================================================
 * SECTION 5: STANDALONE DOTS
 * ============================================================================
 */

/** Shared point-extrusion mechanism for blobDot() / freeformBlobDotted():
 * extrude in place (no XY movement) to form a small dome, dwell, retract,
 * lift-press-lift to shed stringing, then (via the caller's next goto())
 * travel to the next spot. `diameter` is the primary user-facing sizing
 * knob; filament amount is DERIVED from it, not passed directly.
 *
 * Volume model: `baseZ` (the nozzle standoff height during extrusion) is
 * physically part of this -- material must first fill the gap between the
 * nozzle tip and the bed (a cylinder of the target diameter and height
 * `baseZ`) before it can dome up above the tip (approximated as a
 * hemisphere on top of that cylinder). So:
 *   volume = pi*r^2*baseZ (standoff cylinder) + (2/3)*pi*r^3 (dome bulge)
 * converted to filament length via FIL_AREA (same conversion used for
 * bead E-rates elsewhere in this file), then scaled by
 * `extrusionMultiplier` -- an explicit manual dial for empirical tuning
 * against real hardware, independent of the geometry model. Default 1.0;
 * raise it if prints still look under-extruded after accounting for
 * `baseZ`. There is no separate height parameter: the resulting dome
 * height is ~diameter/2 above the standoff, which clears the 0.4mm Relief
 * Height Floor (global_printing_parameters.md) for any diameter >= 0.8mm.
 *
 * Anti-stringing: a straight retract-then-lift can leave a thin strand of
 * TPU stretched between the blob apex and the nozzle, which then gets
 * dragged sideways on travel. After the first lift, this presses back
 * down to `baseZ` with NO extrusion (lays the strand flat against the
 * already-deposited blob) before lifting again for the actual travel-safe
 * clearance -- see `troubleshooting.md` (stringing note under blobDot()).
 * `liftZ` should clear the tallest feature nearby before traveling to the
 * next spot -- see troubleshooting.md SS2 (nozzle collision) if these are
 * ever packed closer together than their own height. */
function emitBlobDot(em, cx, cy, {
  diameter = 1.6, baseZ = 0.3, extrudeSpeed = 300, dwellMs = 400,
  extrusionMultiplier = 1.0, liftZ = 2.0, liftSpeed = 600,
  liftDwellMs = 200, pressDwellMs = 150, pressSpeed = 600,
} = {}) {
  const radius = diameter / 2.0;
  const standoffVolume = Math.PI * radius * radius * baseZ;
  const domeVolume = (2 / 3) * Math.PI * radius ** 3;
  const eAmt = ((standoffVolume + domeVolume) / FIL_AREA) * extrusionMultiplier;

  em.goto(cx, cy, baseZ);
  em.unretract();
  em.eTotal += eAmt;
  em.a(`G1 E${em.eTotal.toFixed(4)} F${extrudeSpeed}`);
  em.dwell(dwellMs);
  em.retract();

  const zLift = baseZ + liftZ;
  em.a(`G1 Z${zLift.toFixed(3)} F${liftSpeed}`);
  em.z = zLift;
  em.dwell(liftDwellMs);

  // press any stretched strand back down onto the blob, no extrusion
  em.a(`G1 Z${baseZ.toFixed(3)} F${pressSpeed}`);
  em.z = baseZ;
  em.dwell(pressDwellMs);

  em.a(`G1 Z${zLift.toFixed(3)} F${liftSpeed}`);
  em.z = zLift;
}

/** The DEFAULT dot texture (see texture_patterns.md) -- a single-point
 * "blob" dot, preferred over circularDot() unless a flat, precisely
 * spiral-filled disc is specifically needed. Extrudes filament at one
 * fixed XY position (no lateral movement), dwells, retracts, lifts Z on
 * the same spot, dwells -- see emitBlobDot() above for the mechanism and
 * the diameter -> filament-amount derivation. */
export function blobDot(em, cx, cy, options = {}) {
  em.newPattern();
  emitBlobDot(em, cx, cy, options);
}

/** A single solid circular dot, built by spiraling a fill path outward --
 * an ALTERNATIVE to the default blobDot() when a flat, precisely
 * diameter'd disc is needed (diameter and height are independently
 * controlled here, unlike blobDot()'s derived-from-diameter dome).
 * height should be a multiple of LAYER_HEIGHT (0.2mm) -- e.g. height=0.4
 * -> 2 layers. NOTE: "donut" (hollow-center) shape is NOT implemented --
 * known gap. */
export function circularDot(em, cx, cy, { diameter = 1.6, height = 0.4, speed = 250 } = {}) {
  const nLayers = Math.max(MIN_LAYERS, Math.round(height / LAYER_HEIGHT));
  const pts = spiralDisc([cx, cy], diameter / 2.0);
  em.newPattern();
  emitStroke(em, pts, nLayers, 0.42, speed);
}

// NOTE: "hairy dot" (a single circular dot with one hair strand pulled
// from its center) is NOT implemented -- known gap, see texture_patterns.md.

/**
 * ============================================================================
 * SECTION 6: MULTI-TEXTURE LAYOUT VERIFICATION
 * ============================================================================
 * Every other verification in this library is single-texture (bounds,
 * negative-E, checkerboard adjacency). Nothing checked whether two
 * SEPARATELY-chosen regions physically overlap -- and overlapping regions
 * generate silently, then crash the nozzle into already-printed material
 * during the actual print. This section closes that gap.
 */

/** Returns the overlapping area in mm^2 between two regions (0 if none). */
export function regionOverlapArea(a, b) {
  const xOverlap = Math.max(0, Math.min(a.x0 + a.w, b.x0 + b.w) - Math.max(a.x0, b.x0));
  const yOverlap = Math.max(0, Math.min(a.y0 + a.h, b.y0 + b.h) - Math.max(a.y0, b.y0));
  return xOverlap * yOverlap;
}

/**
 * Checks a list of regions for overlaps and for insufficient clearance.
 * Call this BEFORE generating a multi-texture print, and confirm
 * `ok === true`. Overlaps are hard failures (nozzle collision); gaps
 * smaller than minGap are warnings (features may fuse together).
 *
 * @param regions array of {x0,y0,w,h} -- optionally with a `name` field
 *                for clearer messages
 * @param minGap  minimum desired clearance between regions, mm.
 *                Default 0.5mm -- equal to DEFAULT_WIDTH (one bead), so
 *                this warns only when regions are effectively touching.
 *                Deliberately permissive: overlaps are still hard errors,
 *                but tight-but-separate placements are allowed through.
 *                Raise it (e.g. 10) if features fusing becomes a problem.
 */
export function verifyLayout(regions, { minGap = 0.5, bedMargin = 15.0 } = {}) {
  const errors = [];
  const warnings = [];

  regions.forEach((r, i) => {
    const label = r.name || `region[${i}]`;
    if (r.x0 < bedMargin || r.y0 < bedMargin ||
        r.x0 + r.w > BED_X - bedMargin || r.y0 + r.h > BED_Y - bedMargin) {
      errors.push(
        `${label} at x[${r.x0}-${r.x0 + r.w}] y[${r.y0}-${r.y0 + r.h}] ` +
        `falls outside the safe bed area (${bedMargin}mm margin on a ` +
        `${BED_X}x${BED_Y}mm bed).`
      );
    }
  });

  for (let i = 0; i < regions.length; i++) {
    for (let j = i + 1; j < regions.length; j++) {
      const a = regions[i], b = regions[j];
      const la = a.name || `region[${i}]`, lb = b.name || `region[${j}]`;
      const area = regionOverlapArea(a, b);
      if (area > 0) {
        errors.push(
          `${la} and ${lb} OVERLAP by ${area.toFixed(1)}mm^2 -- the nozzle ` +
          `would crash into already-printed material. Move one of them.`
        );
        continue;
      }
      // no overlap: measure the actual clearance between them
      const xGap = Math.max(a.x0 - (b.x0 + b.w), b.x0 - (a.x0 + a.w));
      const yGap = Math.max(a.y0 - (b.y0 + b.h), b.y0 - (a.y0 + a.h));
      const clearance = Math.max(xGap, yGap);
      if (clearance < minGap) {
        warnings.push(
          `${la} and ${lb} are only ${clearance.toFixed(1)}mm apart ` +
          `(recommended minimum ${minGap}mm) -- adjacent features may fuse.`
        );
      }
    }
  }

  return { ok: errors.length === 0, errors, warnings };
}
